- name: Akto code analysis
  uses: akto-api-security/code-analysis-action@v1
  with:
    AKTO_DASHBOARD_URL: "https://app.akto.io/dashboard/quick-start"
    AKTO_API_KEY: {{ secrets.AKTO_API_KEY }}
    API_COLLECTION_NAME: SQLInjection
